-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Jan 31, 2025 at 03:12 AM
-- Server version: 5.7.39
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `arifinbatik`
--

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `keterangan` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`id`, `name`, `keterangan`) VALUES
(1, 'rainbow', 'rainbow motif'),
(2, 'plain', 'plain'),
(3, 'smoke', 'smoke motif');

-- --------------------------------------------------------

--
-- Table structure for table `produk`
--

CREATE TABLE `produk` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `material` varchar(50) NOT NULL,
  `motif` varchar(50) NOT NULL,
  `color` varchar(50) NOT NULL,
  `deskripsi` varchar(500) NOT NULL,
  `category_id` int(11) NOT NULL,
  `gambar` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `produk`
--

INSERT INTO `produk` (`id`, `name`, `material`, `motif`, `color`, `deskripsi`, `category_id`, `gambar`) VALUES
(1, 'batik stamp ', 'cotton/rayon', 'lung-lungan', 'blue', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Blue is a high-quality batik fabric from the Rainbow Batik collection, with an alluring lung-lungan motif that is full of philosophy. Made from soft and comfortable cotton/rayon, this fabric comes in a classic blue color that gives an elegant and calming impression. Suitable for various purposes such as clothing, crafts, or decoration, this batik combines the beauty of tradition and modern style in one special product.', 1, '1.png'),
(2, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow is a high-quality batik fabric from the Rainbow Batik collection, with graceful and beautiful floral motifs. Made from soft and comfortable cotton/rayon, this fabric comes in a bright yellow color that gives a fresh and cheerful impression. Suitable for various purposes such as clothing, crafts, or decoration, this batik combines the beauty of tradition and a modern touch in one special product.', 1, '2.png'),
(3, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black is a high-quality batik fabric with a combination of simple floral motifs and elegant plain touches. Made from soft and comfortable cotton/rayon, this fabric comes in a classic black color that gives a luxurious and versatile impression. Suitable for various needs such as formal wear, crafts, or decoration, this batik combines traditional style with a minimalist modern look.', 2, '3.png'),
(5, 'batik stamp ', 'catton/rayon', 'abstrak', 'blue', 'Batik Stamp Cotton/Rayon \"Abstract\" - Blue is a premium batik fabric featuring a unique smoke pattern with an artistic touch. Made from soft and comfortable cotton/rayon material, this fabric comes in a stunning blue color, offering an elegant and modern look. Perfect for various uses, including clothing, crafts, or decorations, this batik combines traditional charm with contemporary style in one exceptional product.', 3, '4.png'),
(6, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black is a high-quality batik fabric from the Rainbow Batik collection, featuring an elegant floral motif. Made from soft and comfortable cotton/rayon material, this fabric showcases a classic black color with a touch of vibrant design, creating a balance between sophistication and modern charm. Perfect for clothing, crafts, or decorative purposes, this batik embodies the beauty of tradition with a contemporary twist.', 1, '5.png'),
(7, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'green', 'Batik Stamp Cotton/Rayon \"Flower\" - Green is a premium batik fabric featuring a vibrant rainbow motif blended with an elegant floral design. Crafted from soft and comfortable cotton/rayon material, this fabric showcases a refreshing green base that exudes a sense of harmony and liveliness. Ideal for clothing, crafts, or decorative purposes, this batik combines traditional artistry with modern flair, making it a standout addition to any collection.', 1, '6.png'),
(8, 'batik stamp ', 'catton/rayon', 'abstrak', 'orange', 'Batik Stamp Cotton/Rayon \"Abstract\" - Orange is a premium batik fabric featuring a striking abstract design on a vibrant orange background. Made from soft and comfortable cotton/rayon material, this fabric offers both elegance and boldness with its plain, yet dynamic color. Perfect for various uses such as clothing, crafts, or décor, this batik combines traditional stamping techniques with a modern and artistic twist, making it a versatile and eye-catching choice.', 2, '7.png'),
(9, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Rainbow is a premium fabric featuring intricate floral patterns on a vibrant yellow base, enhanced with captivating rainbow accents. Made from soft and breathable cotton/rayon, it combines traditional stamping techniques with modern, colorful aesthetics. This versatile fabric is perfect for crafting stylish clothing, unique décor, or creative projects that stand out with elegance and charm.', 1, '8.png'),
(10, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a premium fabric featuring delicate floral patterns on a classic black background. Made from soft and durable cotton/rayon, this fabric exudes timeless elegance with its minimalist yet refined design. Perfect for clothing, crafts, or décor, it offers versatility and sophistication, making it an excellent choice for any project.', 2, '9.png'),
(11, 'batik stamp ', 'catton/rayon', 'flower', 'purple', 'Batik Stamp Cotton/Rayon \"Flower\" - Purple Rainbow is a premium fabric showcasing elegant floral patterns on a rich purple background, beautifully accented with vibrant rainbow hues. Crafted from soft and breathable cotton/rayon material, it blends traditional artistry with modern color dynamics. Perfect for clothing, décor, or creative crafts, this versatile fabric adds a touch of charm and sophistication to any project.', 1, '10.png'),
(12, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'blue', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Blue Smoke is a premium fabric featuring intricate vine-inspired patterns in shades of blue, subtly blended with a smoky accent for a timeless and elegant look. Made from soft and durable cotton/rayon material, it offers both comfort and sophistication. Perfect for clothing, home décor, or creative crafts, this versatile fabric combines traditional artistry with a modern, understated style.', 3, '11.png'),
(13, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Rainbow is a premium fabric featuring intricate floral patterns on a vibrant blue background, beautifully enhanced with rainbow accents. Made from soft and breathable cotton/rayon, this fabric offers a perfect blend of traditional craftsmanship and modern color aesthetics. Ideal for clothing, décor, or creative projects, it adds a touch of elegance and vibrancy to any design.', 1, '12.png'),
(14, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring intricate floral patterns on a calming blue background. Made from soft, breathable cotton/rayon, this fabric is both comfortable and durable, perfect for various projects. Whether you\'re designing clothing, home décor, or crafts, its timeless elegance and versatility make it an ideal choice. The rich blue tone combined with the detailed floral design offers a sophisticated and modern touch to any creation.', 2, '13.png'),
(15, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Rainbow is a premium fabric featuring intricate floral patterns on a rich brown background, beautifully complemented with vibrant rainbow accents. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. Its versatile design makes it perfect for various applications such as clothing, home décor, or crafts. The warm brown tones and colorful rainbow highlights bring a unique, artistic flair to any project', 1, '14.png'),
(16, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Plain is a premium fabric featuring delicate floral patterns on a vibrant yellow background. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. Its bright yellow hue adds a cheerful touch, while the intricate floral design brings a sense of sophistication. Perfect for various applications such as clothing, home décor, or crafts, this fabric offers versatility and timeless beauty for any creative project.', 2, '15.png'),
(17, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Smoke is a premium fabric showcasing delicate floral patterns on a calming blue background with a subtle smoke effect. Made from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The blend of blue tones with the smoky accents creates a serene and sophisticated design. Perfect for various applications such as clothing, home décor, or crafts, this fabric brings a modern yet timeless touch to any creative project.', 3, '16.png'),
(18, 'batik stamp ', 'catton/rayon', 'flower', 'blue, black', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue and Black Plain is a premium fabric that blends delicate floral patterns with a striking combination of blue and black. Made from soft, breathable cotton/rayon, this fabric offers comfort and elegance. The simple yet bold color contrast enhances the floral design, making it perfect for creating stylish clothing, home décor, or crafts. With its versatile and timeless aesthetic, this fabric adds a touch of sophistication to any project.', 2, '17.png'),
(19, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring intricate floral patterns on a serene blue background. Made from soft and breathable cotton/rayon, this fabric provides both comfort and elegance. The calming blue tone, combined with delicate floral motifs, creates a versatile design suitable for various applications such as clothing, home décor, or crafts. Its timeless appeal and subtle beauty make it an ideal choice for adding sophistication and charm to any project.', 2, '18.png'),
(20, 'batik stamp ', 'catton/rayon', 'flower', 'purple', 'Batik Stamp Cotton/Rayon \"Flower\" - Purple Plain is a premium fabric showcasing delicate floral patterns on a rich purple background. Made from soft and breathable cotton/rayon, this fabric combines comfort with elegance. The vibrant purple tone complements the intricate floral design, offering a sophisticated and timeless aesthetic. Perfect for clothing, home décor, or crafts, this versatile fabric adds a touch of luxury and charm to any creative project.', 2, '19.png'),
(21, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Rainbow is a premium fabric featuring intricate floral patterns on a warm brown background, accented with vibrant rainbow hues. Made from soft and breathable cotton/rayon, this fabric offers comfort, durability, and a unique blend of traditional craftsmanship with modern flair. Perfect for clothing, home décor, or crafts, the rich brown base and colorful rainbow details create an eye-catching design that adds a lively, sophisticated touch to any project.', 1, '20.png'),
(22, 'batik stamp ', 'catton/rayon', 'flower', 'green', 'Batik Stamp Cotton/Rayon \"Flower\" - Green Plain is a premium fabric featuring intricate floral patterns on a refreshing green background. Made from soft and breathable cotton/rayon, this fabric offers both comfort and elegance. The vibrant green hue enhances the floral design, creating a harmonious and calming effect. Ideal for clothing, home décor, or crafts, this versatile fabric adds a touch of natural beauty and sophistication to any project.', 2, '21.png'),
(23, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring delicate floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. The rich red tone enhances the intricate floral design, creating a vibrant yet sophisticated look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a striking and timeless touch to any creative project.', 2, '22.png'),
(24, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a premium fabric featuring intricate floral patterns on a warm brown background. Made from soft and breathable cotton/rayon, this fabric offers both comfort and elegance. The earthy brown tone complements the delicate floral design, creating a harmonious and timeless aesthetic. Ideal for clothing, home décor, or crafts, this versatile fabric brings a touch of warmth and sophistication to any project.', 2, '23.png'),
(25, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring delicate floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. The rich red tone enhances the intricate floral design, creating a vibrant yet sophisticated look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a striking and timeless touch to any creative project.', 2, '24.png'),
(26, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Rainbow is a premium fabric featuring intricate floral patterns on a vibrant blue background, highlighted by colorful rainbow accents. Made from soft and breathable cotton/rayon, this fabric blends traditional craftsmanship with modern aesthetics. The bold combination of blue and rainbow colors adds a cheerful and dynamic flair, making it perfect for creating stylish clothing, home décor, or unique crafts.', 1, '25.png'),
(27, 'batik stamp ', 'catton/rayon', 'shell', 'creame', 'Batik Stamp Cotton/Rayon \"Shell\" - Cream Plain is a premium fabric featuring a subtle shell-inspired design on a soft cream background. Made from soft, breathable cotton/rayon, this fabric offers comfort and elegance. The light cream tone provides a neutral, timeless base, while the delicate shell pattern adds a touch of sophistication. Perfect for clothing, home décor, or crafts, this versatile fabric brings a refined and elegant touch to any project.', 2, '26.png'),
(28, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Rainbow is a premium fabric featuring intricate floral patterns on a bright yellow background, enhanced with vibrant rainbow accents. Made from soft and breathable cotton/rayon, this fabric combines comfort with lively color. The cheerful yellow tone, paired with the colorful rainbow highlights, creates a vibrant and eye-catching design. Perfect for clothing, home décor, or crafts, this versatile fabric adds a joyful and artistic touch to any project.', 1, '27.png'),
(29, 'batik stamp ', 'catton/rayon', 'abstrak', 'purple', 'Batik Stamp Cotton/Rayon \"Abstract\" - Purple Smoke is a premium fabric featuring an abstract design in shades of purple, complemented by a subtle smoky effect. Made from soft and breathable cotton/rayon, this fabric offers both comfort and sophistication. The rich purple tones, combined with the smoky accents, create a modern, artistic look that adds depth and elegance to any project. ', 3, '28.png'),
(30, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Rainbow is a premium fabric featuring intricate floral patterns on a bold red background, enhanced with vibrant rainbow accents. Made from soft and breathable cotton/rayon, this fabric combines comfort with striking color. The deep red tone, complemented by the colorful rainbow highlights, creates a lively and eye-catching design. Perfect for clothing, home décor, or crafts, this versatile fabric adds a touch of boldness and creativity to any project.', 1, '29.png'),
(31, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'blue', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Blue Rainbow is a premium fabric featuring intricate lung-lungan patterns on a vibrant blue background, enhanced with lively rainbow accents. Made from soft, breathable cotton/rayon, this fabric combines comfort with a modern, colorful design. The deep blue tone and vibrant rainbow hues create a dynamic and eye-catching effect, perfect for clothing, home décor, or creative crafts.', 1, '30.png'),
(32, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Rainbow is a premium fabric featuring intricate floral patterns on a warm brown background, beautifully accented with vibrant rainbow hues. Made from soft and breathable cotton/rayon, this fabric combines comfort with an eye-catching design. The earthy brown tone complements the colorful rainbow accents, creating a harmonious and dynamic look.', 1, '31.png'),
(33, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Plain is a premium fabric featuring delicate floral patterns on a vibrant yellow background. Made from soft and breathable cotton/rayon, this fabric offers both comfort and elegance. The bright yellow tone creates a cheerful and lively atmosphere, while the intricate floral design adds sophistication and charm. Ideal for various applications such as clothing, home décor, or crafts, this versatile fabric brings a joyful and timeless touch to any project.', 2, '32.png'),
(34, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Smoke is a premium fabric featuring intricate floral patterns on a serene blue background, enhanced with a subtle smoky effect. Made from soft and breathable cotton/rayon, this fabric offers both comfort and sophistication. The calming blue tones, combined with the smoky accents, create a unique and modern aesthetic. Perfect for clothing, home décor, or crafts, this versatile fabric adds an artistic and elegant touch to any project.', 3, '114.png'),
(35, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring intricate floral patterns on a tranquil blue background. Made from soft and breathable cotton/rayon, this fabric offers both comfort and elegance. The serene blue tone enhances the delicate floral design, creating a harmonious and sophisticated look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a timeless and refreshing touch to any project.', 2, '33.png'),
(36, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring delicate floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. The rich red hue enhances the intricate floral design, creating a vibrant and sophisticated look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a striking and timeless touch to any project, making it a perfect choice for those seeking a bold and artistic design.', 2, '34.png'),
(37, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring delicate floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. The rich red hue enhances the intricate floral design, creating a vibrant and sophisticated look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a striking and timeless touch to any project, making it a perfect choice for those seeking a bold and artistic design.', 2, '35.png'),
(38, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring delicate floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. The rich red hue enhances the intricate floral design, creating a vibrant and sophisticated look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a striking and timeless touch to any project, making it a perfect choice for those seeking a bold and artistic design.', 2, '36.png'),
(39, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Plain is a premium fabric featuring delicate floral patterns on a bright yellow background. Made from soft, breathable cotton/rayon, this fabric combines comfort and elegance. The vibrant yellow tone brings a cheerful and lively atmosphere, while the intricate floral design adds sophistication. Perfect for clothing, home décor, or crafts, this versatile fabric adds a joyful and timeless touch to any project.', 2, '37.png'),
(40, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'brown', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Brown Plain is a premium fabric showcasing the traditional lung-lungan pattern on a rich brown background. Made from soft and breathable cotton/rayon, this fabric offers both comfort and elegance. The earthy brown hue adds warmth and versatility, while the lung-lungan design adds depth and texture to the fabric. Ideal for clothing, home décor, or crafts, this versatile fabric brings a timeless and sophisticated touch to any project.', 2, '38.png'),
(41, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'black', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Black Plain is a premium fabric featuring the traditional lung-lungan pattern on a bold black background. Made from soft, breathable cotton/rayon, this fabric combines comfort with elegance. The deep black tone enhances the lung-lungan design, creating a striking contrast that adds sophistication and modern flair. Perfect for clothing, home décor, or crafts, this versatile fabric brings a timeless and artistic touch to any project.', 2, '39.png'),
(42, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring intricate floral patterns on a calming blue background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The peaceful blue tone complements the delicate floral design, creating a serene and sophisticated aesthetic. Perfect for clothing, home décor, or crafts, this versatile fabric adds a refreshing and timeless touch to any project', 2, '40.png'),
(43, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a premium fabric featuring intricate floral patterns on a striking black background. Made from soft, breathable cotton/rayon, this fabric combines comfort and elegance. The deep black tone highlights the delicate floral design, creating a bold yet sophisticated aesthetic. Perfect for clothing, home décor, or crafts, this versatile fabric adds a dramatic and timeless touch to any project.', 2, '41.png'),
(44, 'batik stamp ', 'catton/rayon', 'flower', 'purple', 'Batik Stamp Cotton/Rayon \"Flower\" - Purple Rainbow is a premium fabric featuring intricate floral patterns on a vibrant purple background, accented with colorful rainbow hues. Made from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The rich purple tone is beautifully complemented by the lively rainbow accents, creating a dynamic and joyful design. Perfect for clothing, home décor, or crafts, this versatile fabric adds a bold, artistic touch to any project, ', 1, '42.png'),
(45, 'batik stamp ', 'catton/rayon', 'abstrak', 'blue', 'Batik Stamp Cotton/Rayon \"Abstract\" - Blue Smoke is a premium fabric featuring a unique abstract design in various shades of blue, blended with soft, smoky accents. Made from soft and breathable cotton/rayon, this fabric offers comfort while maintaining an elegant and contemporary look. The cool blue tones, combined with the smoky effect, evoke a sense of tranquility and modern artistry. Perfect for clothing, home décor, or crafts, this versatile fabric brings a sophisticated', 3, '43.png'),
(46, 'batik stamp ', 'catton/rayon', 'abstrak', 'orange, black', 'Batik Stamp Cotton/Rayon \"Abstract\" - Orange and Black Smoke is a premium fabric featuring a bold abstract design with vibrant orange and deep black hues, accented by a smoky effect. Made from soft, breathable cotton/rayon, this fabric combines comfort with a striking, modern aesthetic. The vibrant orange contrasts beautifully with the dark black tones, while the smoky accents add depth and intrigue to the design. Perfect for clothing, home décor, or crafts', 3, '44.png'),
(47, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring intricate floral patterns on a calming blue background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The peaceful blue tone complements the delicate floral design, creating a serene and sophisticated aesthetic. Perfect for clothing, home décor, or crafts, this versatile fabric adds a refreshing and timeless touch to any project.', 2, '45.png'),
(48, 'batik stamp ', 'catton/rayon', 'line', 'black', 'Batik Stamp Cotton/Rayon \"Line\" - Black Plain is a premium fabric featuring a simple yet striking line pattern on a deep black background. Made from soft and breathable cotton/rayon, this fabric combines comfort with a modern, minimalist aesthetic. The clean lines create a bold contrast against the black base, offering a sleek and timeless design. Perfect for clothing, home décor, or crafts, this versatile fabric adds a sophisticated and contemporary touch to any project', 2, '46.png'),
(49, 'batik stamp ', 'catton/rayon', 'flower', 'purple', 'Batik Stamp Cotton/Rayon \"Flower\" - Purple Plain is a premium fabric featuring intricate floral patterns on a rich purple background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The deep purple tone enhances the delicate floral design, creating a vibrant and sophisticated look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a timeless and luxurious touch to any project.', 2, '47.png'),
(50, 'batik stamp ', 'catton/rayon', 'coconut tree', 'blue', 'Batik Stamp Cotton/Rayon \"Coconut Tree\" - Blue Rainbow is a premium fabric featuring a tropical coconut tree design set against a serene blue background, with vibrant rainbow accents. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a lively, playful aesthetic. The soothing blue tones are complemented by the colorful rainbow hues, creating a cheerful and dynamic look. Perfect for clothing, home décor, or crafts.', 1, '48.png'),
(51, 'batik stamp ', 'catton/rayon', 'flower', 'green', 'Batik Stamp Cotton/Rayon \"Flower\" - Green Plain is a premium fabric featuring delicate floral patterns on a fresh green background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a natural, serene aesthetic. The vibrant green tone enhances the intricate floral design, creating a harmonious and peaceful look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a refreshing and timeless touch to any project.', 2, '49.png'),
(52, 'batik stamp ', 'catton/rayon', 'animal', 'red', 'Batik Stamp Cotton/Rayon \"Animal\" - Red Smoke is a premium fabric featuring bold animal-inspired patterns on a striking red background, accented with subtle smoky effects. Made from soft, breathable cotton/rayon, this fabric combines comfort with a fierce, modern aesthetic. The vivid red tones provide a powerful backdrop to the intricate animal designs, while the smoky accents add depth and intrigue to the overall look. Perfect for clothing, home décor, or crafts.', 3, '50.png'),
(53, 'batik stamp ', 'catton/rayon', 'flower', 'orange', 'Batik Stamp Cotton/Rayon \"Flower\" - Orange Plain is a premium fabric featuring delicate floral patterns on a vibrant orange background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The bright orange tone brings warmth and energy, while the intricate floral design adds sophistication. Perfect for clothing, home décor, or crafts, this versatile fabric adds a cheerful and timeless touch to any project.', 2, '51.png'),
(54, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a premium fabric featuring intricate floral patterns on a warm brown background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a sophisticated, earthy aesthetic. The rich brown tone enhances the delicate floral design, creating a timeless and elegant look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a cozy.', 2, '52.png'),
(55, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Rainbow is a premium fabric featuring intricate floral patterns on a bold black background, accented with vibrant rainbow hues. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a striking, dynamic aesthetic. The deep black backdrop provides a dramatic contrast to the colorful rainbow accents, creating a bold and lively look. Perfect for clothing, home décor, or crafts.', 1, '53.png'),
(56, 'batik stamp ', 'catton/rayon', 'flower', 'green', 'Batik Stamp Cotton/Rayon \"Flower\" - Green Plain is a premium fabric featuring delicate floral patterns on a soothing green background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a refreshing, nature-inspired aesthetic. The soft green tone enhances the intricate floral design, creating a calm and harmonious look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a peaceful and timeless touch to any project.', 2, '54.png'),
(57, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Plain is a premium fabric featuring beautiful floral patterns on a bright yellow background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a lively and cheerful aesthetic. The vibrant yellow tone enhances the delicate floral design, creating an uplifting and warm look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a joyful and timeless touch to any project', 2, '55.png'),
(58, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Plain is a premium fabric featuring beautiful floral patterns on a bright yellow background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a lively and cheerful aesthetic. The vibrant yellow tone enhances the delicate floral design, creating an uplifting and warm look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a joyful and timeless touch to any project', 2, '56.png'),
(59, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a premium fabric featuring intricate floral patterns on a rich brown background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a warm, earthy aesthetic. The deep brown tone enhances the delicate floral design, creating a sophisticated and timeless look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a cozy, natural touch to any project.', 2, '57.png'),
(60, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring intricate floral patterns on a calming blue background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The serene blue tone beautifully complements the delicate floral design, creating a tranquil and sophisticated look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a timeless and peaceful touch to any project.', 2, '58.png'),
(61, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring delicate floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a vibrant and striking aesthetic. The rich red tone enhances the intricate floral design, creating a dynamic and elegant look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and timeless touch to any project.', 2, '59.png'),
(62, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Rainbow is a premium fabric featuring intricate floral patterns set against a bold red background, complemented by vibrant rainbow accents. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a lively, dynamic aesthetic. The deep red tone serves as a striking backdrop to the colorful rainbow hues, creating a joyful and energetic design. Perfect for clothing, home décor, or crafts, this versatile fabric adds a fun.', 1, '60.png'),
(63, 'batik stamp ', 'catton/rayon', 'animal', 'blue', 'Batik Stamp Cotton/Rayon \"Animal\" - Blue Smoke is a premium fabric featuring bold animal-inspired patterns on a soothing blue background, enhanced by subtle smoky accents. Made from soft, breathable cotton/rayon, this fabric combines comfort with a modern, artistic flair. The calming blue tones contrast beautifully with the mysterious smoky effects, creating a design that is both dynamic and tranquil. Perfect for clothing, home décor, or crafts.', 3, '61.png'),
(64, 'batik stamp ', 'catton/rayon', 'shell', 'green', 'Batik Stamp Cotton/Rayon \"Shell\" - Green Plain is a premium fabric featuring a unique shell design on a soft green background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a fresh, natural aesthetic. The gentle green tone provides a soothing backdrop for the intricate shell motifs, creating a harmonious and peaceful look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a touch of nature and elegance to any project.', 2, '62.png'),
(65, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a premium fabric featuring delicate floral patterns on a striking black background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a bold, elegant aesthetic. The rich black tone provides a dramatic contrast to the intricate floral design, creating a sophisticated and timeless look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a refined and luxurious touch to any project.', 2, '63.png'),
(66, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Plain is a premium fabric featuring delicate floral patterns on a bright yellow background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a cheerful and lively aesthetic. The vibrant yellow tone enhances the intricate floral design, creating a warm and welcoming look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a bright, sunny touch to any project.', 2, '64.png'),
(67, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring beautiful floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a striking, dynamic aesthetic. The rich red tone serves as a vibrant backdrop for the intricate floral design, creating a passionate and elegant look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and timeless touch to any project.', 2, '65.png'),
(68, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring beautiful floral patterns on a bold red background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a striking, dynamic aesthetic. The rich red tone serves as a vibrant backdrop for the intricate floral design, creating a passionate and elegant look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and timeless touch to any project.', 2, '66.png'),
(69, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a premium fabric featuring intricate floral patterns on a deep black background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and sophistication. The bold black tone enhances the delicate floral design, creating a striking contrast that adds elegance and drama. Perfect for clothing, home décor, or crafts, this versatile fabric provides a timeless and refined look.', 2, '67.png'),
(70, 'batik stamp ', 'catton/rayon', 'flower', 'purple', 'Batik Stamp Cotton/Rayon \"Flower\" - Purple Plain is a premium fabric featuring beautiful floral patterns on a rich purple background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a luxurious, vibrant aesthetic. The deep purple tone enhances the delicate floral design, creating a sophisticated and elegant look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a regal and timeless touch to any project.', 2, '68.png'),
(71, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'green', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Green Rainbow is a premium fabric featuring the traditional lung-lungan pattern with vibrant rainbow accents set against a soothing green background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a lively, dynamic aesthetic. The combination of green with the colorful rainbow highlights creates a cheerful and eye-catching design. Perfect for clothing, home décor, or crafts.', 1, '69.png'),
(72, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a sophisticated fabric featuring delicate floral motifs on a deep black background. Crafted from soft, breathable cotton/rayon, this fabric offers both comfort and elegance. The rich black backdrop enhances the intricate floral design, creating a bold yet refined look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a timeless, luxurious touch to any project.', 1, '70.png'),
(73, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a premium fabric featuring intricate floral patterns on a warm brown background. Made from soft, breathable cotton/rayon, this fabric offers comfort and a timeless, earthy aesthetic. The rich brown tone enhances the delicate floral design, creating a sophisticated and natural look. Perfect for clothing, home décor, or crafts, this versatile fabric adds an elegant, cozy touch to any project.', 2, '71.png'),
(74, 'batik stamp ', 'catton/rayon', 'flower', 'green', 'Batik Stamp Cotton/Rayon \"Flower\" - Green Plain is a premium fabric featuring beautiful floral patterns on a serene green background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a calming, nature-inspired aesthetic. The gentle green tone enhances the delicate floral design, creating a harmonious and fresh look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a peaceful, earthy touch to any project.', 2, '72.png'),
(75, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring intricate floral patterns on a vibrant red background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a bold, eye-catching aesthetic. The rich red tone beautifully contrasts with the delicate floral design, creating a dynamic and elegant look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and timeless touch to any project.', 2, '73.png'),
(76, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring intricate floral patterns on a vibrant red background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a bold, eye-catching aesthetic. The rich red tone beautifully contrasts with the delicate floral design, creating a dynamic and elegant look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and timeless touch to any project.', 2, '74.png'),
(77, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring intricate floral patterns on a vibrant red background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a bold, eye-catching aesthetic. The rich red tone beautifully contrasts with the delicate floral design, creating a dynamic and elegant look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and timeless touch to any project.', 2, '75.png'),
(78, 'batik stamp ', 'catton/rayon', 'shell', 'black', 'Batik Stamp Cotton/Rayon \"Shell\" - Black Plain is a premium fabric featuring subtle shell designs on a deep black background. Made from soft, breathable cotton/rayon, this fabric offers comfort and a refined aesthetic. The dark black tone enhances the delicate shell motifs, creating a sophisticated and modern look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a touch of elegance and understated beauty to any project.', 2, '76.png'),
(79, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring intricate floral patterns on a vibrant red background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a bold, eye-catching aesthetic. The rich red tone beautifully contrasts with the delicate floral design, creating a dynamic and elegant look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and timeless touch to any project.', 2, '77.png'),
(80, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Plain is a premium fabric featuring delicate floral patterns on a bright yellow background. Made from soft, breathable cotton/rayon, this fabric offers comfort and a cheerful, lively aesthetic. The vibrant yellow tone complements the intricate floral design, creating a warm and inviting look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a fresh and timeless touch to any project.', 2, '78.png'),
(81, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Smoke is a premium fabric featuring elegant floral patterns on a soft blue background with a subtle smoky effect. Made from soft, breathable cotton/rayon, this fabric combines comfort with a tranquil, ethereal aesthetic. The serene blue tone, complemented by the smoky accents, creates a sophisticated and calming design. Perfect for clothing, home décor, or crafts, this versatile fabric adds a delicate, artistic touch to any project.', 3, '79.png'),
(82, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring delicate floral patterns on a calming blue background. Made from soft, breathable cotton/rayon, this fabric offers comfort and a serene aesthetic. The smooth blue tone enhances the intricate floral design, creating a tranquil and timeless look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a peaceful and elegant touch to any project', 2, '80.png'),
(83, 'batik stamp ', 'catton/rayon', 'flower', 'yellow', 'Batik Stamp Cotton/Rayon \"Flower\" - Yellow Smoke is a premium fabric featuring intricate floral patterns set against a vibrant yellow background with a soft smoky overlay. Made from soft, breathable cotton/rayon, this fabric combines comfort with a unique, artistic flair. The bright yellow tone is elegantly complemented by the smoky accents, giving the fabric a dynamic and mysterious charm. Ideal for clothing, home décor, or crafts.', 3, '81.png'),
(84, 'batik stamp ', 'catton/rayon', 'flower', 'purple', 'Batik Stamp Cotton/Rayon \"Flower\" - Purple Rainbow is a premium fabric featuring intricate floral patterns on a rich purple background, enhanced with vibrant rainbow accents. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a bold, artistic aesthetic. The deep purple tone provides a striking backdrop for the colorful rainbow hues, creating a lively and energetic design. Perfect for clothing, home décor, or crafts, this versatile fabric adds a playful.', 1, '82.png'),
(85, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a premium fabric featuring delicate floral patterns on a rich black background. Crafted from soft, breathable cotton/rayon, this fabric offers comfort combined with an elegant and timeless aesthetic. The deep black backdrop allows the intricate floral design to stand out, creating a striking contrast that adds sophistication and depth. Ideal for clothing, home décor, or crafts.', 2, '83.png'),
(86, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a premium fabric featuring beautiful floral patterns on a serene blue background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a calm and timeless aesthetic. The soft blue tone enhances the intricate floral design, creating a peaceful and sophisticated look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a touch of elegance and tranquility to any project.', 2, '84.png'),
(87, 'batik stamp ', 'catton/rayon', 'flower', 'purple, orange', 'Batik Stamp Cotton/Rayon \"Flower\" - Purple, Orange, Smoke is a premium fabric featuring an elegant floral design on a vibrant mix of purple and orange, complemented by a subtle smoky effect. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a bold, artistic aesthetic. The rich purple and orange tones blend beautifully, while the smoky accents add depth and sophistication. Ideal for clothing, home décor, or crafts.', 3, '85.png'),
(88, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a premium fabric featuring delicate floral designs set against a bold black background. Crafted from soft and breathable cotton/rayon, this fabric provides both comfort and a refined aesthetic. The striking contrast between the intricate floral patterns and the deep black backdrop creates a sophisticated, timeless look. Perfect for clothing, home décor, or crafts, this versatile fabric adds an elegant and understated touch to any project.', 2, '86.png'),
(89, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'orange', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Orange Smoke is a premium fabric featuring a vibrant lung-lungan pattern on a warm orange background, with a subtle smoky effect that enhances its unique design. Made from soft, breathable cotton/rayon, this fabric offers both comfort and an artistic, modern aesthetic. The bold orange tone, combined with the smoky accents, creates a dynamic and contemporary look. Perfect for clothing, home décor, or crafts.', 3, '87.png'),
(90, 'batik stamp ', 'catton/rayon', 'flower', 'green', 'Batik Stamp Cotton/Rayon \"Flower\" - Green Plain is a premium fabric featuring intricate floral designs on a soft green background. Made from soft, breathable cotton/rayon, this fabric offers comfort along with a fresh, natural aesthetic. The serene green backdrop enhances the delicate floral patterns, creating a calm and harmonious look. Ideal for clothing, home décor, or crafts, this versatile fabric adds an elegant, earthy touch to any project.', 2, '88.png'),
(91, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a premium fabric showcasing elegant floral patterns on a warm brown background. Crafted from soft, breathable cotton/rayon, this fabric provides both comfort and a rich, earthy aesthetic. The deep brown backdrop complements the intricate floral designs, creating a sophisticated and timeless look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a cozy yet refined touch to any project.', 2, '89.png'),
(92, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric featuring delicate floral designs set against a vibrant red background. Made from soft, breathable cotton/rayon, this fabric combines comfort with bold, eye-catching aesthetics. The rich red hue enhances the intricate floral patterns, creating a striking yet elegant look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a touch of passion and vibrancy to any project', 2, '90.png'),
(93, 'batik stamp ', 'catton/rayon', 'mirror', 'yellow', 'Batik Stamp Cotton/Rayon \"Mirror\" - Yellow Rainbow is a premium fabric that features a striking mirror pattern on a vibrant yellow background, complemented by a beautiful rainbow spectrum. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a lively, artistic aesthetic. The bright yellow backdrop enhances the vivid rainbow colors, creating a dynamic and cheerful design. Perfect for clothing, home décor, or crafts.', 1, '91.png'),
(94, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'red', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Red Plain is a premium fabric featuring the bold lung-lungan pattern on a rich red background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a striking, contemporary aesthetic. The vibrant red backdrop enhances the unique lung-lungan design, creating a dynamic and eye-catching look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a lively and modern touch to any projec', 2, '92.png'),
(95, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is a premium fabric featuring intricate floral designs on a deep black background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a sleek, timeless aesthetic. The contrast between the rich black tone and the delicate floral patterns creates a bold yet refined look, making it perfect for those seeking a sophisticated design. Ideal for clothing, home décor.', 2, '93.png');
INSERT INTO `produk` (`id`, `name`, `material`, `motif`, `color`, `deskripsi`, `category_id`, `gambar`) VALUES
(96, 'batik stamp ', 'catton/rayon', 'shell', 'blue', 'Batik Stamp Cotton/Rayon \"Shell\" - Blue Smoke is a luxurious fabric featuring a delicate shell pattern on a soft blue background, accentuated by a gentle smoky effect. Crafted from breathable cotton/rayon, this fabric combines comfort with a unique and refined look. The soft blue backdrop provides a calming atmosphere, while the smoky elements add depth and intrigue to the design. Perfect for creating elegant clothing, home décor, or crafts.', 3, '94.png'),
(97, 'batik stamp ', 'catton/rayon', 'shell', 'red', 'Batik Stamp Cotton/Rayon \"Shell\" -red Smoke is a luxurious fabric featuring a delicate shell pattern on a soft blue background, accentuated by a gentle smoky effect. Crafted from breathable cotton/rayon, this fabric combines comfort with a unique and refined look. The soft blue backdrop provides a calming atmosphere, while the smoky elements add depth and intrigue to the design. Perfect for creating elegant clothing, home décor, or crafts.', 3, '95.png'),
(98, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric that combines delicate floral designs with a rich red background. Crafted from soft, breathable cotton/rayon, this fabric offers both comfort and style. The vibrant red hue serves as a perfect backdrop for the intricate flower patterns, creating a striking contrast that adds boldness and elegance to any project.', 2, '96.png'),
(99, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a premium fabric that features elegant floral patterns set against a warm brown background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a rich, earthy aesthetic. The deep brown hue enhances the delicate floral details, creating a harmonious and sophisticated look. Perfect for clothing, home décor, or crafts, this versatile fabric adds a timeless, natural touch to any project.', 2, '97.png'),
(100, 'batik stamp ', 'catton/rayon', 'flower', 'gray', 'Batik Stamp Cotton/Rayon \"Flower\" - Gray Plain is a refined fabric featuring intricate floral patterns on a soft gray background. Made from soft and breathable cotton/rayon, this fabric combines comfort with a subtle, elegant aesthetic. The neutral gray backdrop highlights the delicate floral designs, creating a sophisticated and versatile look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a touch of understated beauty to any project.', 2, '98.png'),
(101, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a premium fabric that combines intricate floral designs with a rich brown background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and an earthy, natural aesthetic. The warm brown tone complements the detailed floral patterns, creating a sophisticated and harmonious look. Perfect for a variety of applications such as clothing, home décor, or crafts', 2, '100.png'),
(102, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a premium fabric that combines delicate floral designs with a rich red background. Crafted from soft, breathable cotton/rayon, this fabric offers both comfort and style. The vibrant red hue serves as a perfect backdrop for the intricate flower patterns, creating a striking contrast that adds boldness and elegance to any project.', 2, '101.png'),
(103, 'batik stamp ', 'catton/rayon', 'animal', 'gray', 'Batik Stamp Cotton/Rayon \"Animal\" - Gray Plain is a unique fabric featuring an animal-inspired design set against a soothing gray background. Made from soft, breathable cotton/rayon, this fabric combines comfort with an artistic, nature-inspired aesthetic. The subtle gray tone serves as a neutral backdrop, allowing the animal patterns to stand out in a refined and sophisticated manner. Ideal for clothing, home décor, or crafts.', 2, '102.png'),
(104, 'batik stamp ', 'catton/rayon', 'abstrak', 'blue', 'Batik Stamp Cotton/Rayon \"Abstract\" - Blue Plain is a premium fabric featuring an abstract design on a calming blue background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a modern, artistic aesthetic. The deep blue hue serves as a perfect canvas for the unique abstract patterns, creating a dynamic yet serene look. Ideal for clothing, home décor, or crafts, this versatile fabric adds a contemporary touch to any project.', 2, '103.png'),
(105, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'orange', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Orange Plain is a striking fabric featuring the traditional \"lung-lungan\" design on a vibrant orange background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a lively, bold aesthetic. The vivid orange backdrop enhances the intricate lung-lungan patterns, creating a warm and dynamic look. Perfect for a variety of uses, including clothing, home décor, or crafts.', 2, '104.png'),
(106, 'batik stamp ', 'catton/rayon', 'line', 'blue', 'Batik Stamp Cotton/Rayon \"Line\" - Blue Plain is a sophisticated fabric featuring a minimalist line design on a calming blue background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a modern, refined aesthetic. The clean lines stand out against the subtle blue backdrop, creating a sleek and elegant look. Ideal for a variety of uses, including clothing, home décor, or crafts, this versatile fabric adds a contemporary touch to any project.', 2, '105.png'),
(107, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'orange', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Orange Plain is a striking fabric featuring the traditional \"lung-lungan\" design on a vibrant orange background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a lively, bold aesthetic. The vivid orange backdrop enhances the intricate lung-lungan patterns, creating a warm and dynamic look. Perfect for a variety of uses, including clothing, home décor, or crafts.', 2, '106.png'),
(108, 'batik stamp ', 'catton/rayon', 'lung-lungan', 'orange', 'Batik Stamp Cotton/Rayon \"Lung-Lungan\" - Orange Plain is a striking fabric featuring the traditional \"lung-lungan\" design on a vibrant orange background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a lively, bold aesthetic. The vivid orange backdrop enhances the intricate lung-lungan patterns, creating a warm and dynamic look. Perfect for a variety of uses, including clothing, home décor, or crafts.', 2, '107.png'),
(109, 'batik stamp ', 'catton/rayon', 'flower', 'red', 'Batik Stamp Cotton/Rayon \"Flower\" - Red Plain is a stunning fabric that features delicate floral motifs set against a rich red background. Made from soft and breathable cotton/rayon, this fabric blends comfort with vibrant, eye-catching design. The bold red hue highlights the intricate flower patterns, creating a striking contrast that brings warmth and elegance to any project. Perfect for a variety of applications including clothing, home décor.', 2, '108.png'),
(110, 'batik stamp ', 'catton/rayon', 'flower', 'black', 'Batik Stamp Cotton/Rayon \"Flower\" - Black Plain is an elegant fabric featuring intricate floral patterns set against a sleek black background. Made from soft, breathable cotton/rayon, this fabric combines comfort with a sophisticated, timeless aesthetic. The deep black tone provides a striking contrast that makes the delicate flower designs stand out, creating a refined and modern look. Ideal for various applications such as clothing, home décor.', 2, '109.png'),
(111, 'batik stamp ', 'catton/rayon', 'flower', 'green', 'Batik Stamp Cotton/Rayon \"Flower\" - Green Plain is a beautiful fabric that combines delicate floral patterns with a refreshing green background. Made from soft and breathable cotton/rayon, this fabric offers both comfort and a vibrant, nature-inspired aesthetic. The soothing green backdrop highlights the intricate floral designs, creating a balanced and serene look. Ideal for a variety of applications such as clothing, home décor.', 2, '110.png'),
(112, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Plain is a charming fabric that features elegant floral motifs set against a serene blue background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a calm, soothing aesthetic. The tranquil blue hue enhances the intricate flower patterns, creating a harmonious and refined look. Perfect for a variety of applications, including clothing, home décor', 2, '111.png'),
(113, 'batik stamp ', 'catton/rayon', 'flower', 'blue', 'Batik Stamp Cotton/Rayon \"Flower\" - Blue Smoke is an elegant fabric featuring intricate floral patterns set against a soft blue background with a smoky effect. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a sophisticated, modern aesthetic. The smoky blue tone adds a touch of depth, while the floral designs provide a delicate contrast, creating a refined and calming look. Ideal for various applications such as clothing, home décor,', 3, '112.png'),
(114, 'batik stamp ', 'catton/rayon', 'flower', 'brown', 'Batik Stamp Cotton/Rayon \"Flower\" - Brown Plain is a warm and earthy fabric featuring beautiful floral patterns set against a rich brown background. Made from soft, breathable cotton/rayon, this fabric offers both comfort and a natural, rustic aesthetic. The deep brown hue enhances the intricate floral designs, creating a balanced and cozy look. Perfect for a variety of applications, including clothing, home décor.', 2, '113.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `produk`
--
ALTER TABLE `produk`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `produk`
--
ALTER TABLE `produk`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=115;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `produk`
--
ALTER TABLE `produk`
  ADD CONSTRAINT `produk_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
